---
- name: Create Borg user
  ansible.builtin.user:
    name: borg
    shell: /bin/bash
    create_home: true
- name: Create .ssh
  ansible.builtin.file:
    path: /home/borg/.ssh
    owner: borg
    group: borg
    mode: "0700"
    state: directory
- name: Create authorized_keys
  ansible.builtin.file:
    path: /home/borg/.ssh/authorized_keys
    owner: borg
    group: borg
    mode: '0600'
    state: touch
- name: Copie public ssh-key
  ansible.builtin.copy:
    src: ~/26_kopie/roles/install_server_folder/files/client/home/borg/.ssh/id_rsa.pub
    dest: /home/borg/.ssh/authorized_keys
- name: Create directory backup
  ansible.builtin.file:
    path: /var/backup
    owner: borg
    group: borg
    state: directory
    mode: '0600'
- name: Create filesystem
  ansible.builtin.filesystem:
    fstype: ext4
    dev: /dev/sdc
    uuid: random
- name: Mount /var/backup
  ansible.posix.mount:
    path: /var/backup
    src: /dev/sdc
    fstype: ext4
    state: mounted
  notify:
    - Delete lost+found
- name: Set access for Borg
  command: chown -R borg:borg /var/backup
...